CREATE DATABASE CADE_MINHA_CASA;

/*
Siga a ordem para criar as tabelas
*/

CREATE TABLE USUARIOS(
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_COMPLETO VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    SENHA CHAR(32) NOT NULL
);

CREATE TABLE IMOV_ABAN_VER(
    ID_IMOVEL INT PRIMARY KEY AUTO_INCREMENT,
    IMAGEM TINYTEXT,
    LOGRADOURO VARCHAR(60) NOT NULL,
    NUMERO INT NOT NULL,
    COMPLEMENTO VARCHAR(80),
    BAIRRO VARCHAR(30) NOT NULL,
    CEP CHAR(9) NOT NULL
);

CREATE TABLE IMOV_ABAN_SIN(
    ID_IMOVEL INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    LOGRADOURO VARCHAR(60) NOT NULL,
    NUMERO INT NOT NULL,
    COMPLEMENTO VARCHAR(80),
    BAIRRO VARCHAR(30) NOT NULL,
    CEP CHAR(9) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

/*
Viva la vida
*/